### ISSUE TITLE
Component conflict with MatDatepickerModule

### ISSUE THREAD

**Issue by andreicojea** [brauliodavid/mat-daterangepicker#1]
Hello there 😁 I really liked your picker, it's the only one I could find that's consistent with the datepicker from angular material.

I have a problem though, it seems to have conflicting components with the original MatDatepickerModule, might be due to reexporting it from your module 🤔 

![image](https://user-images.githubusercontent.com/4705022/84902206-2b491380-b0b5-11ea-9f81-5d97d970af81.png)

**Comment by andreicojea** [comment]
not sure why, but it didn't complain when built locally 🤔 is there a chance that you didn't publish your last changes to npm?

**Comment by brauliodavid** [comment]
Hello, you were right, there was an error causing sometimes that issue. I fixed it and published a new version, download it.

**Comment by andreicojea** [comment]
Now I've got a different error 👀 

![image](https://user-images.githubusercontent.com/4705022/84997201-ed043080-b156-11ea-9cd4-0b0f717b9e5d.png)

**Comment by LatinAmerica** [comment]
Can you please reproduce the error in a demo repo? what is the angular version you use?

**Comment by brauliodavid** [comment]
Can you please reproduce the error in a demo repo? what is the angular version you use?
